import { Artwork, CreatorProfile } from './types';

export const LUNA_CREATIVE: CreatorProfile = {
  username: 'luna_creative',
  displayName: 'Luna Creative',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA89R9GxRFfzHadQFI69I6P3Jcfb7YVD_nqkdbvleFNDkJLiz4xGjGoAqkUqtjkgl-2KTiSVycor00dLAr2GxKvHCxM4T_OSdxqe5A2RcOKtL6WTu3XNL5-qPUsY0Z0ueKefEVH09vRzkKryx1XXdCxITTuDUQMXt8lqv2GbeX2Z9e5PgmL7H4NJgPZ5w7a-u7y3Dv3c1ArZ3HYX3s2wAcW6AjZNGWdBUAGHLc7gTgEFP-8v5AfskpX-7ByYdSVcRk0_JFqQU4j289x',
  isVerified: true,
  bio: 'Digital architect exploring the intersection of surrealism and high-fidelity texture. Specialized in Photoshop compositing and generative remixing.',
  remixesCount: '12.4k',
  downloadsCount: '85.2k',
  creationsCount: '158',
};

export const INITIAL_ARTWORKS: Artwork[] = [
  {
    id: 'neon-echoes',
    title: 'Neon Echoes',
    author: 'Aether_Design',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDdJtjq-zsVq2Dbk0xJ4gnrN4xxnnm5InyudL6DjGJsiHaFZSZrDiUaaVTKCFoXfsxISLFkaRJZGKkLWXP9OkBRzgwdDArYfQGEZdNvvzXTRG1oqob__avfpyE5wc-yd4fFBvgIgZY5lCwMZGbGwGcmyYHnj8ocePljib6JLRjoYJ5qdIlbgQeMHkbGVkbJuNOP86TkNfM793kOzbb2JR1skA9qgVLcVC4BSqRtaFHD5JW3E0iE4acQWlbG0TJ81oKT9IHOE5SE2XSI',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGmSMSJgcqdzoJCEJ6UuAxo_OVTkeOkm9Z5TU-aWebpJB-Y1llIZUubfaQWCN9Nnjk4gocWDpKEpTpNRdJ-z5WGjjYS1plvNAaTRs3nawlFvXtovmZf4ewj4Bg4sKHB6A2GybHxob0rHRbO7RhUiIhNJPne8r2_w69W0GBpbgghFc_25xfWm4aiiWmYdDsba5MDj5-trvmweqOOsHz8exm2FTZmQfAcsOkStS-tSlc_pxrL3iqXLBoycq4YuDZAF-vhLVsI46wFxx0',
    description: 'Neon Echoes is an exploration of rhythmic light and architectural silence. Created over a 40-hour session, this piece utilizes advanced lighting layers and glassmorphic depth to create a sense of infinite space within a digital landscape.',
    downloads: '24.5k',
    forks: '1.2k',
    views: '24.5k',
    tags: ['Cyberpunk', 'Glassmorphism', 'Illustration', 'DigitalArt'],
    type: 'Original',
    resolution: '8192 x 4608 PX • 32-BIT COLOR',
    timeAgo: '2 days ago',
  },
  {
    id: 'obsidian-echoes',
    title: 'Obsidian Echoes',
    author: 'luna_creative',
    authorAvatar: LUNA_CREATIVE.avatar,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBeZXDI873WbriS1tALkwkBjb7JtxgsbKdMe6XyuVkuIUTWryk2IaLH24_McCJr32H2sdagaS2xgquZfYXqcS3-w8yzvxrZvM9A10btWCensp3Y0bVelBw44MZ7tZlpyCHrxyNO8SCZ1JYXy53A9cspFnldwdG_juBZ17kwDatvDBSSJrGpYzbYvS-Xm20qAPY3O03XwND6PNXbc6glbwiJwNad-CxpOb2TqZTdOl2XgSopL5hxjDLpkl-bbsiyq7to4NAg5C5TwPiE',
    description: 'A dark surrealist digital painting of a floating obsidian monolith in a desert of white sand under a midnight blue sky with two moons. The lighting is crisp and cool, creating deep shadows and sharp highlights on the geometric monolith.',
    downloads: '1.2k',
    forks: '43',
    views: '8.4k',
    tags: ['Surrealism', 'Monolith', 'Photoshop', 'Desert'],
    type: 'Original',
    resolution: '4096 x 5120 PX • 16-BIT COLOR',
    timeAgo: '3 days ago',
  },
  {
    id: 'circuit-bloom',
    title: 'Circuit Bloom',
    author: 'luna_creative',
    authorAvatar: LUNA_CREATIVE.avatar,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDwVOzJ9afmZAO7He2jdU0dNvW6n6h28_U3muQal0Zts9_wPD-VHkm6szozSpbbfPFhupPq6D2x5IZJXxHdoSQzpjDPVZ1H8LxIWrppNkyk-DmlcGSJr1Sv0qZn60v4h9NTMPaShHx4sFv5CjbqleF9nY7t-IT4M_snATT09vl1JjEPVNVuDd5unMM0iAmEUEarC_gBX8-wrp4MDJhrF53IVPNE7QphkZnJvLADCoQDbrZ4F4vgqO2SK0mZZDmUgquAc36ncb-zqlYG',
    description: 'Intricate digital collage of glowing bioluminescent flora entwined with mechanical copper parts. The background is a deep charcoal gallery space. Electric blue highlights pop against a muted, sophisticated palette.',
    downloads: '2.3k',
    forks: '89',
    views: '12.1k',
    tags: ['Bioluminescent', 'Mechanical', 'Flora', 'DigitalCollage'],
    type: 'Original',
    resolution: '3840 x 4800 PX • 16-BIT COLOR',
    timeAgo: '5 days ago',
  },
  {
    id: 'refraction-point',
    title: 'Refraction Point',
    author: 'luna_creative',
    authorAvatar: LUNA_CREATIVE.avatar,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDcRscc6WOyzd5qXalqtFXBrQAHNhV4io3kX2t8C499vMCXR0iaealWblRd-ULASRkfQWzXEC04WcV9FvhrbEBCTS5CfUUt27FIfillhqxJVeA8S8VzrAi9g39FbRK872y9rsLqmXKeJR7oEeDHAabQpbDRSB_ixH4d7Z4vsOkkkltEIc_3tfZzqQrXp7kwET6vqJ5okLCPHgl_b9wmFxThQgjFzW3pZ2sr1U_223y7-jQSKrORPjeeHv9938DHPtsB2tLmmNjkulL6',
    description: 'Minimalist architectural digital art showing a sharp corner of a glass skyscraper reflecting a violet sunset. The composition is highly geometric and abstract. The lighting is warm and golden, contrasting with the dark, sleek glass surfaces.',
    downloads: '1.9k',
    forks: '54',
    views: '9.8k',
    tags: ['Architecture', 'Skyscraper', 'Reflections', 'Sunset'],
    type: 'Original',
    resolution: '3000 x 3750 PX • 16-BIT COLOR',
    timeAgo: '1 week ago',
  },
  {
    id: 'nebula-weaver',
    title: 'Nebula Weaver',
    author: 'luna_creative',
    authorAvatar: LUNA_CREATIVE.avatar,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA0SK1lYCsFMmrMHBw7-Ivibp5SydUeNxChDWw2bHq61nEjRWm4sGVJIc1BGupQ7SG6gtCslgPZqoloPu2StAV-4A9XdT_8jUPaDuevsgBjXEUheSvCUgR8WE0tAWUb5fAF_K4w7PjOZEcIMV-iAiM7z9tRBjusiNj8xPRL-O453DVd4JwgI4JEX6JpFhLf2w4MI7kLHS5KsWevL9dtyIb8FZpLYimLtMkS74K8Xd5xY3QM4VM9R9wJctnOzJWnliYtHvBtJilDJlxC',
    description: 'A portrait of a celestial figure composed entirely of swirling nebulae and star clusters. The character\'s eyes are glowing white dwarf stars. The aesthetic is deep space, high contrast black and electric purples.',
    downloads: '4.5k',
    forks: '124',
    views: '22.4k',
    tags: ['Celestial', 'Nebula', 'SpacePortrait', 'Cinematic'],
    type: 'Original',
    resolution: '4096 x 5120 PX • 32-BIT COLOR',
    timeAgo: '2 weeks ago',
  },
  {
    id: 'mercury-dreams',
    title: 'Mercury Dreams',
    author: 'luna_creative',
    authorAvatar: LUNA_CREATIVE.avatar,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBFz2N2GO1L5oa4HZ-UMkxpkjfB_8snqRlFVFNOhyO6nYZ1rjuYx4eE6ddj14SqeJLu9pqch2-8UQDUjFuQYfx48EbpTxvqQinfjN9L7Lj78hTZpeZIEYCklLeG9jWVJn9cZYU14q3jp1ScFkXbXqbo_WJSMHgt9bHpdC8fZHOaiwq7Of30Z6YT2Hp7bQIl9BCdu8TihopDpy7rJAvK3lOrBHC2LR-L5ke_DnEDELkSTax78YYATIECVsaoAluPzo6tDv1FH8p_Jq5V',
    description: 'A series of floating liquid mercury spheres suspended in a pitch-black void. The spheres reflect a distant, vibrant neon city. The textures are incredibly smooth and hyper-realistic.',
    downloads: '3.1k',
    forks: '76',
    views: '15.6k',
    tags: ['Mercury', 'LiquidMetal', 'Reflections', 'Sleek'],
    type: 'Original',
    resolution: '3840 x 4800 PX • 16-BIT COLOR',
    timeAgo: '3 weeks ago',
  },
  {
    id: 'silk-anomaly',
    title: 'Silk Anomaly',
    author: 'luna_creative',
    authorAvatar: LUNA_CREATIVE.avatar,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBggTDqDAv4d7_dAxlqLddaRuTctPS_afi7YZPwNGqF3z24l3cBBpLvaBy22J8DBxFsAK8FD4iAhO2arD2P2WQiDGbxIY6o-Ew31DHu3RaJJROoP9hoMjaapbHXRFpbLTpnnWm5001TGSJ4t6CdiC7zL_5XMxx0Q5OMabPSWm_WIYUr5x970y8pZo8yvjDg1lDHGaVjaJH3P2DMEt_gwH9Jn7IUZ2aXQTKb_vO37FzndTqkJGFzId7qeQCEk5GVUiT-ozGAWMb0P8-i',
    description: 'Abstract digital creation of layered translucent silk fabrics floating in zero gravity. The colors are muted tones of charcoal, slate, and bone white. The lighting is soft and ethereal, passing through the layers of fabric.',
    downloads: '1.5k',
    forks: '32',
    views: '7.2k',
    tags: ['Abstract', 'Silk', 'ZeroGravity', 'Ethereal'],
    type: 'Original',
    resolution: '3600 x 4500 PX • 16-BIT COLOR',
    timeAgo: '1 month ago',
  },
  {
    id: 'void-structure',
    title: 'Void Structure',
    author: 'archon',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA1gT1cYNdEBZvExSbpIzr8dX1r_7rsLE4KhwhdcQUk7sPPZsAJ0htOtpSc1o0yKku-Og9osmvg4lSnOaZLdT7n2LRYPGxEg9JdMjts21vFr7Wq4sKqXtGMfSA_dw3XSGVWrIGWNMM2kELLSlRu4Mgt3GkvgmtqXnk91MgwuaUl36T9ad3r7JLxUS--qbj-GEph0OsLcPd3w1r8ih3AFP1-Sn5fGMWB2izvJSWvskN6aEWkZRg435OwIOBtEWCLjakusP3gSfZuwAgL',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDpriIFolLwOMR6d4VcaHgiMuyQ4Of4qpsAlBGqsjE-KCoviG5Lt2n0owfd382ljpiiyFbtQT360mcbjxe8DeqCBs-_KERGOJgfBVPyFa3kzW71oB0oqWT59UnTH1Zy2pi_pK6EOIzEG20aPJNHKAOS6q8ybXygdY0NNLBqdX_d2XWr7x4OtPRcHPL70GpkN2Zz57qdV8E0cLerCqvocgEOFjbe0a0VG2OFDwr1_uqckZjVQ_tzaixrb6s3n2FBfR_JIknajuHs67PC',
    description: 'A minimalist architectural poster design featuring brutalist concrete structures against a deep indigo sky. A single point of light casts long, dramatic shadows. The aesthetic is clean, precise, and professional.',
    downloads: '840',
    forks: '12',
    views: '4.2k',
    tags: ['Brutalist', 'Concrete', 'Architecture', 'Indigo'],
    type: 'Original',
    resolution: '3200 x 4000 PX • 16-BIT COLOR',
    timeAgo: '4 days ago',
  },
  {
    id: 'entropy-flow',
    title: 'Entropy Flow',
    author: 'flux_gen',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAM-k4flcK9xiM1SViZLMoUFM38zSqZc0QXVrdpPGAR_yyrFtO_ibuufv89TBfSZURcCi0iiCGh-N7sJD4MU_JTg0_7uuZ23R0qxe9D_zDNBerCnPR_FinxY7bQ0G-ONcm36BYwSVKikpmsTDPZLDW8WCLUrVHf6iMYRf2oYRmO4XYtcn2WrfYrRWGmHXtDOI0P5v0vMLMloLCFk_ZBp87lyY0aHj4s4prXD9k2aV7YZUugjXZzXYjJcwmDOCdiYBf7-UHx3HW6opQs',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAHSDrn0rOuejQ5dXTu6nhEaVc-IU_w48cWIhyEvkE-Wdg2d074Dj6cw5OROVZy5iVrjwubpW268kcDyVAqEtxYatkpI-O04qFXmDY4VWuZiIVQ7JUiTvau-cOE4SeZN6tjd8S_hkksAw5JBNZqcBEthYZFusqhgd34wbdZYqhjd3OemVg7P5we6XexQs9-x1YfwTfulOttZuG5W4cwXmM4CPJrK0HaBRi0QSfrsNbbRX7LX65AJoyUo0Zpzv5wUiQOcopJFlYShGLp',
    description: 'Vibrant generative artwork consisting of millions of colored particles forming a galactic swirl. The palette transitions from deep magenta to electric blue. Sharp focus, high contrast against a pitch-black background.',
    downloads: '2.5k',
    forks: '156',
    views: '18.9k',
    tags: ['Generative', 'Particles', 'Cosmic', 'Galactic'],
    type: 'Original',
    resolution: '5120 x 6400 PX • 32-BIT COLOR',
    timeAgo: '6 days ago',
  },
  {
    id: 'light-fracture',
    title: 'Light Fracture',
    author: 'optics',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC8oet0kH4K4M-_qG1by3ivkuhvczKfIe4sj4LtLZsvU9bh-84GtXuyA1_QGiyWr2pEVhBcknD726izo75wax5-wy9TGNxxH9mdIPk8c2sJ4GqjsG2r9gSfbD1uUu_KU8XzZGV0T1lUxVxXU6V4QWES4JG-PAd1S4H3xoyRUJzYoLfCdiaB0ubAcRBmJtJeOOJlz5zpsADtIF55fkOofYPj5owIp4kQNUY7NhSGR_EOzEHRJNJHrGEb-1eFYoNWqKctOF9EIJhjyD_B',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-aAHb-eHFRvfhFvdx-dPkr-3ysJ-aTw2ZBUps8flz5mEtRhp1UatDLdCuwfxb5BHLmbXC1dq1WXGaP4DH4FwLC7iet8W06-h7z7BUUL4nDL40KMW7-0SO7y8dyersShKO8z-z5MSqscsCX38WVG0Y4cVU9v5Pz_gZBCFiF14yp0fMt36kQc4hythG0BhKOUVi1Jw270SKrTJJRvPFEzapSgG-3fdA0lCo20UPE61ejlVEU-6lsHB8Fn4FElL_sQp193y1IppO6ObY',
    description: 'A 3D render of a futuristic glass prism refracting white light into a sharp rainbow spectrum. The prism sits on a mirrored black surface. The lighting is extremely sharp and clean, emphasizing optical perfection.',
    downloads: '620',
    forks: '8',
    views: '3.1k',
    tags: ['3DRender', 'Prism', 'Refraction', 'Rainbow'],
    type: 'Original',
    resolution: '3840 x 4800 PX • 16-BIT COLOR',
    timeAgo: '1 week ago',
  },
  {
    id: 'cyber-typo',
    title: 'Cyber Typo',
    author: 'grid_lock',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDdJtjq-zsVq2Dbk0xJ4gnrN4xxnnm5InyudL6DjGJsiHaFZSZrDiUaaVTKCFoXfsxISLFkaRJZGKkLWXP9OkBRzgwdDArYfQGEZdNvvzXTRG1oqob__avfpyE5wc-yd4fFBvgIgZY5lCwMZGbGwGcmyYHnj8ocePljib6JLRjoYJ5qdIlbgQeMHkbGVkbJuNOP86TkNfM793kOzbb2JR1skA9qgVLcVC4BSqRtaFHD5JW3E0iE4acQWlbG0TJ81oKT9IHOE5SE2XSI',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFywSfUFTnWYDQemA_zBF7hGppT3Fj2Kv76cKJP54o_LeInZX8HqgCqJC5B13q-exW1EQE4Ruv7u08H0MXdzNYDzvbbhqdIZAdbfZHDr9uOxK_WP9AcXBKYURv3djHB-d9WfeGW6NR2i8lHDJ4PKSyazhJ7aMGtlgJk5ZQS6c3R2xQ9bjlteIa3koPGPG0kU1uSpjqSu_VXWMA7517CcUaFN_j7ZuYWtJi70_K6z8T9J6dpYgl0ehwO_GHLEbQ327m5vHk6V2dAN4l',
    description: 'A futuristic poster design with bold typography and a central glowing orb. High-contrast monochromatic scheme with one vibrant orange accent. The style is influenced by Swiss design and sci-fi brutalism.',
    downloads: '3.1k',
    forks: '210',
    views: '14.2k',
    tags: ['Cyberpunk', 'Typography', 'SwissDesign', 'Poster'],
    type: 'Original',
    resolution: '3000 x 4000 PX • 16-BIT COLOR',
    timeAgo: '1 week ago',
  },
  {
    id: 'silver-sands',
    title: 'Silver Sands',
    author: 'tactile',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA89R9GxRFfzHadQFI69I6P3Jcfb7YVD_nqkdbvleFNDkJLiz4xGjGoAqkUqtjkgl-2KTiSVycor00dLAr2GxKvHCxM4T_OSdxqe5A2RcOKtL6WTu3XNL5-qPUsY0Z0ueKefEVH09vRzkKryx1XXdCxITTuDUQMXt8lqv2GbeX2Z9e5PgmL7H4NJgPZ5w7a-u7y3Dv3c1ArZ3HYX3s2wAcW6AjZNGWdBUAGHLc7gTgEFP-8v5AfskpX-7ByYdSVcRk0_JFqQU4j289x',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAIk79MTHthdYbLubTX7F5Vj7737mCuY9D40vssQvj7RFp5xvFpyeej6i5VfKxuRgJgIQdfe78TTSTgMwcaFvAw_cxgkrnYQ7KsvnE6HUClNlz9QDYAGQkPgD_Y7bgLG4-HzRoP_wUkmPa6cWrWIzsia3O1vLp1NmVFeweIRswsgMCMeHxZ5dGYsRtAwY1EbVHRewICuLypIhXlPytmAQwyVhKsyQQqMe2zEbjFxxlaN1xbC_5RxohkAR_9hCb4cAxe64_ry3k_4Wx6',
    description: 'Deep texture study of digital sand ripples in charcoal and silver. Top-down view with high-contrast directional lighting. The grains appear tactile and razor-sharp.',
    downloads: '940',
    forks: '22',
    views: '5.1k',
    tags: ['TextureStudy', 'Minimalist', 'Silver', 'Tactile'],
    type: 'Original',
    resolution: '3800 x 4750 PX • 16-BIT COLOR',
    timeAgo: '2 weeks ago',
  },

  // Neon Echoes Remixes:
  {
    id: 'crimson-echoes',
    title: 'Crimson Echoes',
    author: 'Vector_Void',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAM-k4flcK9xiM1SViZLMoUFM38zSqZc0QXVrdpPGAR_yyrFtO_ibuufv89TBfSZURcCi0iiCGh-N7sJD4MU_JTg0_7uuZ23R0qxe9D_zDNBerCnPR_FinxY7bQ0G-ONcm36BYwSVKikpmsTDPZLDW8WCLUrVHf6iMYRf2oYRmO4XYtcn2WrfYrRWGmHXtDOI0P5v0vMLMloLCFk_ZBp87lyY0aHj4s4prXD9k2aV7YZUugjXZzXYjJcwmDOCdiYBf7-UHx3HW6opQs',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBi-WwW2ttUC0G0KgZof0lCqjp5FuczZlc6E1ZV7D_4CT69AWVPDZNdfJcRrkjI9xlfDntML2Vd7O8hCTJQXTvhCU9aHVYkmjqAMc3xofW-3o2ngf0jVyeFtc4P15v9h7XTrhqo0lO20jt72J6km1qslgW0Gy2fI0fuqXo98E2qR-vDixqJl8rUqKyv8HbJ2ETuszoXdaq8ZJ_OIAqbmByjaQ6BxzGR8VUswi1GPVI6dklZYfPmF6hYRoMdGBJmZwycdqeRWUJImW2n',
    description: 'A remix of Neon Echoes featuring a high-contrast black and white version with sharp glowing red accents. The architectural lines are emphasized with electric red wireframe details on top of charcoal surfaces.',
    downloads: '1.2k',
    forks: '12',
    views: '8.4k',
    tags: ['Crimson', 'Wireframe', 'Architectural', 'Minimalist'],
    type: 'Remix',
    parentArtworkId: 'neon-echoes',
    parentAuthor: 'Aether_Design',
    timeAgo: '1 day ago',
  },
  {
    id: 'solar-silence',
    title: 'Solar Silence',
    author: 'Lume_Art',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA89R9GxRFfzHadQFI69I6P3Jcfb7YVD_nqkdbvleFNDkJLiz4xGjGoAqkUqtjkgl-2KTiSVycor00dLAr2GxKvHCxM4T_OSdxqe5A2RcOKtL6WTu3XNL5-qPUsY0Z0ueKefEVH09vRzkKryx1XXdCxITTuDUQMXt8lqv2GbeX2Z9e5PgmL7H4NJgPZ5w7a-u7y3Dv3c1ArZ3HYX3s2wAcW6AjZNGWdBUAGHLc7gTgEFP-8v5AfskpX-7ByYdSVcRk0_JFqQU4j289x',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBaie4eHev5BfiOKVb7Rmn8PzAVW2gnmaOLm1hSiHjrGQs55OxIXcj2Bl8-9UiEjq06p0aqiBGVK58ng-nzEpif-LZHZwXjvihxH1_XF1D_kM84CEdYa3mHza7cRzBydAKudlx9FcSyyHQ0zOmpoGe1ZTI7-b5zFjPvwA-RZZlZmc7yEfH7mV_SgK1n7KuGMNzeBJPqG40OZVmeFfRxvqtPvqRx8l_nnDUmG7f6AiAmaIzeazOD6-nzydsI0-OxKVzyTsXpQFD__hy0',
    description: 'A remix of Neon Echoes with a solarized, high-key palette. The scene is transformed into a bright, airy architectural dreamscape with soft lavender and gold highlights against a pristine white background.',
    downloads: '950',
    forks: '4',
    views: '4.8k',
    tags: ['Solarized', 'Dreamscape', 'Ethereal', 'Light'],
    type: 'Remix',
    parentArtworkId: 'neon-echoes',
    parentAuthor: 'Aether_Design',
    timeAgo: '1 day ago',
  },
  {
    id: 'data-decay',
    title: 'Data Decay',
    author: 'Pixel_Punk',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAM-k4flcK9xiM1SViZLMoUFM38zSqZc0QXVrdpPGAR_yyrFtO_ibuufv89TBfSZURcCi0iiCGh-N7sJD4MU_JTg0_7uuZ23R0qxe9D_zDNBerCnPR_FinxY7bQ0G-ONcm36BYwSVKikpmsTDPZLDW8WCLUrVHf6iMYRf2oYRmO4XYtcn2WrfYrRWGmHXtDOI0P5v0vMLMloLCFk_ZBp87lyY0aHj4s4prXD9k2aV7YZUugjXZzXYjJcwmDOCdiYBf7-UHx3HW6opQs',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCJ_xpKVxyisf0dBsGa_VCbVq0jHl9tGiyX_WTTLom2W8V2dvbdFKmOtP-s2cXSiNlWVaugGvIn9xnFnUXy1ETfHHL2tDpGGv39LFDu3URRzQomy-Rc6wDRBNXkqDHj-C2ZExOOIihZ4BeptUQLp73S0tXIlBrzAxEZUJMT8fBIavqzdHkrYqxbYY62Q9VQkAgMzxCJp1XpVZ8dodAhNfRD09yHtK90GvuK0QlX2bXhNuH2GVmEkcXfk5M91Os2O3io6BZoYfaG8Dij',
    description: 'A glitch-art remix of Neon Echoes. The original city landscape is fractured with digital artifacts, chromatic aberration, and data-moshing textures. High energy and chaotic.',
    downloads: '1.4k',
    forks: '18',
    views: '9.2k',
    tags: ['GlitchArt', 'ChromaticAberration', 'Cybernetic', 'Chaotic'],
    type: 'Remix',
    parentArtworkId: 'neon-echoes',
    parentAuthor: 'Aether_Design',
    timeAgo: '12 hours ago',
  },
  {
    id: 'wireframe-city',
    title: 'Wireframe City',
    author: 'Draft_Master',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC8oet0kH4K4M-_qG1by3ivkuhvczKfIe4sj4LtLZsvU9bh-84GtXuyA1_QGiyWr2pEVhBcknD726izo75wax5-wy9TGNxxH9mdIPk8c2sJ4GqjsG2r9gSfbD1uUu_KU8XzZGV0T1lUxVxXU6V4QWES4JG-PAd1S4H3xoyRUJzYoLfCdiaB0ubAcRBmJtJeOOJlz5zpsADtIF55fkOofYPj5owIp4kQNUY7NhSGR_EOzEHRJNJHrGEb-1eFYoNWqKctOF9EIJhjyD_B',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDeTLcJafAPGYaAlNZM2eNtzOe2O0qzM9rwDu5dL4_1A8pvPuPVK5CdmLTu4KS-dO4Sz-3WTnA-8lE-9QEvQkspOVqoni33JqObBspb1QOZ1LXme8c37D4kfrjCRh2PoWzgwuPSnGmpbrJU8jvkxB-VvVN5EzlzVuaWU6Sh8xorSb6ATKDKFOBhekU2npymVtL7K55sVQmS-8r7P92mJ8PQSy38gCJHi-gH0aQkiMIS0vHrEU23EJQyjO-L2_SxhaNfdeULzhIScexq',
    description: 'A minimalist line-art remix of Neon Echoes. The complex 3D architecture is reduced to thin, glowing electric blue lines on a pitch black background. Very high contrast and clean.',
    downloads: '1.1k',
    forks: '27',
    views: '7.4k',
    tags: ['LineArt', 'Minimalist', 'Blueprint', 'Technical'],
    type: 'Remix',
    parentArtworkId: 'neon-echoes',
    parentAuthor: 'Aether_Design',
    timeAgo: '2 days ago',
  }
];
